server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/booking
            - Method=POST
          filters:
            - SetPath=/api/booking
        - id: booking-service-all
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/booking
            - Method=GET
          filters:
            - SetPath=/api/booking/all
        - id: place-service
          uri: http://${PLACE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/place
          filters:
            - SetPath=/api/place
        - id: travel-service
          uri: http://${TRAVEL_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/travel
          filters:
            - SetPath=/api/travel
        - id: weather-service
          uri: http://${WEATHER_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/weather
          filters:
            - SetPath=/api/weather