name: Build and deliver containers

on: push

jobs:
  bookingservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver booking-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./booking-service
        run: mvn package -B

      - name: Docker login
        run: docker login -u ${{ secrets.luckyboi61 }} -p ${{ secrets.RQpfGvedV7pdfnd }}

      - name: Docker Build
        run: docker build -t ${{ secrets.luckyboi61 }}/booking-service:latest ./booking-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.luckyboi61 }}/booking-service:latest
  placeservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver place-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./place-service
        run: mvn package -B

      - name: Docker login
        run: docker login -u ${{ secrets.luckyboi61 }} -p ${{ secrets.RQpfGvedV7pdfnd }}

      - name: Docker Build
        run: docker build -t ${{ secrets.luckyboi61 }}/place-service:latest ./place-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.luckyboi61 }}/place-service:latest
  travelservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver travel-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./travel-service
        run: mvn package -B

      - name: Docker login
        run: docker login -u ${{ secrets.luckyboi61 }} -p ${{ secrets.RQpfGvedV7pdfnd }}

      - name: Docker Build
        run: docker build -t ${{ secrets.luckyboi61 }}/travel-service:latest ./travel-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.luckyboi61 }}/travel-service:latest
  weatherservice:
    runs-on: ubuntu-latest
    name: Java 17 build, test, deliver weather-service container
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: adopt

      - name: Build, test and package project
        working-directory: ./weather-service
        run: mvn package -B

      - name: Docker login
        run: docker login -u ${{ secrets.luckyboi61 }} -p ${{ secrets.RQpfGvedV7pdfnd }}

      - name: Docker Build
        run: docker build -t ${{ secrets.luckyboi61 }}/weather-service:latest ./weather-service

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.luckyboi61 }}/weather-service:latest